"""Type stubs for the Rust extension module."""

import uuid

class CrockfordUUID:
    """UUID held as 16 raw bytes, rendered as Crockford Base32."""

    def __init__(self, value: str | bytes | uuid.UUID) -> None: ...
    @property
    def bytes(self) -> bytes: ...
    @property
    def uuid(self) -> uuid.UUID: ...
    def __bytes__(self) -> bytes: ...
    @classmethod
    def generate_v4(cls) -> CrockfordUUID: ...
    @classmethod
    def generate_v7(cls) -> CrockfordUUID: ...

def encode_crockford(b: bytes) -> str: ...
def decode_crockford(s: str) -> bytes: ...
